### ISSUE TITLE
redundant css

### ISSUE THREAD

**Issue by clubkemp** [magedabdelsalam/code-refactoring#3]
I'm actually not sure if this is out of the scope of this assignment, but you still have a bit of redundant CSS What I mean by that is for example

`.search-engine-optimization {
    margin-bottom: 20px;
    padding: 50px;
    height: 300px;
    font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
    background-color: #0072bb;
    color: #ffffff;
}

.online-reputation-management {
    margin-bottom: 20px;
    padding: 50px;
    height: 300px;
    font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
    background-color: #0072bb;
    color: #ffffff;
}

.social-media-marketing {
    margin-bottom: 20px;
    padding: 50px;
    height: 300px;
    font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
    background-color: #0072bb;
    color: #ffffff;
}`

All three of these are essentially doing the same thing, they are just each targeting a different html element. SO you could change the classes of the html elements to be the same class, and target it once in css

**Comment by magedabdelsalam** [comment]
There's a ton of redundant CSS. I also called the wrong h in the footer. Should be h4 not h3. Just fixed it. Thank you!
